apiVersion: v1
kind: Service
metadata:
  name: statuspage-placeholder
  namespace: status-page
spec:
  selector:
    app: statuspage-placeholder
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

