name: CI/CD Build, Push to ECR, Deploy to EKS

on:
  push:
    branches:
      - CICD

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t dr_repo_statuspage ./status-page

      - name: Tag Docker image
        run: docker tag dr_repo_statuspage:latest 992382545251.dkr.ecr.us-east-1.amazonaws.com/dr_repo_statuspage:latest

      - name: Push Docker image
        run: docker push 992382545251.dkr.ecr.us-east-1.amazonaws.com/dr_repo_statuspage:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Restore kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/dr-statuspage \
            dr-statuspage-app=992382545251.dkr.ecr.us-east-1.amazonaws.com/dr_repo_statuspage:latest \
            -n default

      - name: Verify rollout
        run: kubectl rollout status deployment/dr-statuspage -n default

